import type { EmbedBuilder } from "discord.js";
import type { Newspaper, NewspaperContent } from "@/lib/types";

/** Chaos brand color used for newspaper embeds (an electric blue). */
const NEWSPAPER_COLOR = 0x1f8bff;

/** Discord hard-limits an embed field value to 1024 characters. */
const FIELD_VALUE_LIMIT = 1024;
/** Discord hard-limits an embed description to 4096 characters. */
const DESCRIPTION_LIMIT = 4096;

/**
 * Dynasty banner image. Overridable via `NEWSPAPER_IMAGE_URL` so a league can
 * point at their own artwork without a code change.
 */
function newspaperImageUrl(): string | undefined {
  return process.env.NEWSPAPER_IMAGE_URL?.trim() || undefined;
}

/** Truncate text to `limit` characters, appending an ellipsis when clipped. */
function truncate(text: string, limit: number): string {
  return text.length <= limit ? text : `${text.slice(0, limit - 1)}…`;
}

/** Render the highlights list as a Discord-friendly bulleted block. */
function formatHighlights(highlights: string[]): string {
  if (highlights.length === 0) {
    return "_No standout storylines this week._";
  }
  return truncate(
    highlights.map((line) => `• ${line}`).join("\n"),
    FIELD_VALUE_LIMIT,
  );
}

/** Render the power poll as a numbered ranking with optional notes. */
function formatPowerPoll(content: NewspaperContent): string | undefined {
  const poll = content.powerPoll;
  if (!poll || poll.length === 0) {
    return undefined;
  }

  const lines = poll.map((entry) => {
    const note = entry.note ? ` — ${entry.note}` : "";
    return `**${entry.rank}.** ${entry.team}${note}`;
  });

  return truncate(lines.join("\n"), FIELD_VALUE_LIMIT);
}

/**
 * Build the rich newspaper embed. discord.js runtime classes are imported
 * dynamically (matching `readyMessage.ts`) so this module can be loaded without
 * eagerly pulling in the server-external discord.js package.
 */
export async function buildNewspaperEmbed(
  newspaper: Newspaper,
): Promise<EmbedBuilder> {
  const { EmbedBuilder } = await import(/* webpackIgnore: true */ "discord.js");
  const { content } = newspaper;

  const embed: EmbedBuilder = new EmbedBuilder()
    .setTitle(truncate(`📰 ${content.headline}`, 256))
    .setDescription(truncate(content.summary, DESCRIPTION_LIMIT))
    .setColor(NEWSPAPER_COLOR)
    .setAuthor({ name: `CHAOS Dynasty Weekly — Week ${newspaper.weekNumber}` })
    .setFooter({ text: `Generated by ${newspaper.model}` })
    .setTimestamp(new Date(newspaper.generatedAt));

  embed.addFields({
    name: "🔥 Highlights",
    value: formatHighlights(content.highlights),
  });

  const powerPoll = formatPowerPoll(content);
  if (powerPoll) {
    embed.addFields({ name: "🏈 Chaos Power Poll", value: powerPoll });
  }

  const imageUrl = newspaperImageUrl();
  if (imageUrl) {
    embed.setThumbnail(imageUrl);
  }

  return embed;
}
